imports:
    - { resource: search_post.yml }

parameters:
    pp_acme.post.repository.class: PP\AcmeBundle\Entity\PostRepository
    pp_acme.post.provider.class: PP\AcmeBundle\Service\PostProvider
    pp_acme.orm.query_result.pagination.class: PP\AcmeBundle\Orm\PaginationQueryResult
    pp_acme.orm.query_result.basic.class: PP\AcmeBundle\Orm\BasicQueryResult

services:
   pp_acme.post.repository:
        class: %pp_acme.post.repository.class%
        factory_service:  doctrine.orm.entity_manager
        factory_method:   getRepository
        arguments:
            - "PPAcmeBundle:Post"

   pp_acme.query_result.pagination:
        class: %pp_acme.orm.query_result.pagination.class%
        arguments:
            - @request_stack
            - @knp_paginator

   pp_acme.query_result.basic:
        class: %pp_acme.orm.query_result.basic.class%

   pp_acme.post.provider:
        class: %pp_acme.post.provider.class%
        arguments:
            - @event_dispatcher
            - @pp_acme.post.repository
            - @pp_acme.query_result.pagination
